### ISSUE TITLE
Can't install if Django isn't already installed

### ISSUE THREAD

**Issue by LegoStormtroopr** [realpython/django-slow-tests#14]
If you try to install django-slowtests *before* django is installed, it fails. This makes it difficult to include in a tox script when django and django-slowtests are installed concurrently.

![image](https://cloud.githubusercontent.com/assets/2173174/23381784/e2832ac8-fd93-11e6-8050-77a89fd3d67c.png)

**Comment by mjhea0** [comment]
@LegoStormtroopr what would you like to see changed? Want to issue a PR?

**Comment by LegoStormtroopr** [comment]
Part of the problem is in [`setup.py`](https://github.com/realpython/django-slow-tests/blob/master/setup.py#L19), where setup imports django_slowtests:

    version=__import__("django_slowtests").__version__,

which itself imports [django on line 1](https://github.com/realpython/django-slow-tests/blob/master/django_slowtests/__init__.py):

    from django.core.exceptions import ImproperlyConfigured

Thus, on setup it fails if Django isn't already installed.

I'm not sure how you'd want to fix this, but the choices I can see are either:

* just declare the version in setup (probably not great)
* Broaden the exception testing to catch everything (also not great)
* Just import `DiscoverSlowestTestsRunner` without trying to catch anything (why are you catching anyway)
* Or a fourth something else I can't think of

**Comment by mjhea0** [comment]
Looks like this is a bigger issue with Tox in general -> https://github.com/tox-dev/tox/issues/42.

**Comment by LegoStormtroopr** [comment]
I disagree with that assessment. The screen shot shows I can replicate this using just plain pip without tox.

I can't see a reason for `setup.py` to depend so heavily on django already being installed to be able run.

I've offered a couple of ways to resolve this. Either way, this is a cool library and I'd love to be able to use it more, but this issue is a blocker for me.

**Comment by mjhea0** [comment]
@LegoStormtroopr thoughts on using `install_requires`?

```
install_requires=['django>=1.5']
```

**Comment by inglesp** [comment]
Instead of importing `django_slowtests `, can you get around this by reading `django_slowtests.__init__.py` and searching for a line containing `__version__`?

**Comment by obestwalter** [comment]
> Looks like this is a bigger issue with Tox in general -> tox-dev/tox#42.

It is arguable if this is a Tox issue, as deps is just calling pip with all the deps and from pips viewpoint it's not a bug, but an [implementation detail](https://github.com/pypa/pip/issues/3480#issuecomment-183010917).

There is a pretty painless workaround though for things like this (unless I am missing something), which is now mentioned in the [tox issue](https://github.com/tox-dev/tox/issues/42#issuecomment-287371306) and which hopefully finds its way into the docs at some point.

**Comment by obestwalter** [comment]
I just saw that @LegoStormtroopr that the same thing ... sorry.

**Comment by mjhea0** [comment]
Fixed! Thanks @inglesp! Just hard coded the version to the *setup.py* file.

**Comment by LegoStormtroopr** [comment]
Thanks! :)
