### ISSUE TITLE
Incorrect test duration recorded when test uses freezegun

### ISSUE THREAD

**Issue by petedmarsh** [realpython/django-slow-tests#16]
I came across this project yesterday and I tried it out on my Django project, I got some strange output:

```
77450953.5910s test_a (some.TestCase)
45914963.3745s test_b (other.TestCase)
...
1.6083s test_c (final.TestCase)
```

Now, my some of my tests are on the slow side but they don't take > 2 years to run!

I remember that some of my test cases use [freezegun](https://github.com/spulec/freezegun) to test date/time sensitive code - I think that's likely the cause.

In my case `other.TestCase.test_b` uses freezegun:

```
class TestCase(TestCase):
    @freeze_time('2016-11-14 10:00')
    def test_b(self):
        #...
```

but `some.TestCase.test_a` does not - and when I run `other.TestCase.test_b` in isolation I get a reasonable recorded duration, so it seems that using freezegun in one test affects the recorded time of another.

**Comment by mjhea0** [comment]
Thanks for letting me know. I need to look at freeze gun and figure out what's going on. Give me a few days.

**Comment by petedmarsh** [comment]
I've had a look myself and I have a patch, will raise a PR later- fairly
simple to fix fortunately!

**Comment by petedmarsh** [comment]
Fix in: https://github.com/realpython/django-slow-tests/pull/17
