### ISSUE TITLE
Not calling setUpClass

### ISSUE THREAD

**Issue by epicserve** [realpython/django-slow-tests#5]
A lot of my tests are failing because the test runner isn't calling [setUpClass](https://docs.djangoproject.com/en/1.8/topics/testing/tools/#django.test.SimpleTestCase). I have a BaseTest class which disconnects a signal using ``setUpClass``.

**Comment by mjhea0** [comment]
@epicserve want to submit a PR to fix? Thanks for catching this!

**Comment by epicserve** [comment]
@mjhea0 You might need to point me in the right direction. I started looking into it and just simply adding the following to ``DiscoverSlowestTestsRunner`` didn't fix it.

```python
@classmethod
    def setUpClass(cls):
        super(TestCase, cls).setUpClass()
```

**Comment by j1z0** [comment]
@epicserve -- I'm guessing that your super call should be
'''
super(DiscoverSlowestTestRunner, cls).setUpClass()
'''

**Comment by epicserve** [comment]
I did the following, which seems to make it start calling setUpClass.

```python
class DiscoverSlowestTestsRunner(DiscoverRunner):
    """
    Runner that extends Django's DiscoverRunner to time the tests.
    """

    test_suite = TimingSuite
```

However now the print out at the end of the run looks like this:

```bash
10 slowest tests:
3.5954s <function _timer at 0x103ed3668>
3.5953s <function _timer at 0x103ed3410>
...
```

**Comment by epicserve** [comment]
I think I need to give up for now. :) BTW, I'm not understanding how in [runtests.py](https://github.com/realpython/django-slow-tests/blob/master/runtests.py) you're even using ``DiscoverSlowestTestsRunner``, because it's never mentioned.

**Comment by lambdacomplete** [comment]
Sorry to chime in on such an old issue but, although I **love** this tool, I believe this has to be highlighted in the README. I spent 3 hours trying to figure out why `setUpClass` was not called, ironically in an attempt to optimize the test suite based on the data collected with django-slow-tests.
